### ISSUE TITLE
Remove all `pprint()` calls from test scripts

### ISSUE THREAD

**Issue by neteler** [mundialis/actinia_statistic_plugin#10]
Can `pprint` be removed? A debug left-over?

_Originally posted by @marcjansen in https://github.com/mundialis/actinia_statistic_plugin/pull/8#discussion_r829237204_

The `pprint()` occurs in the following scripts:

```
tests/test_strds_area_stats.py
tests/test_strds_sample.py
tests/test_vector_sample.py
tests/test_raster_sample.py
tests/test_strds_area_stats_univar.py
tests/test_raster_area_stats_univar.py
tests/test_raster_area_stats.py
```

**Comment by anikaweinmann** [comment]
Can be done if one of the other tickets of the statistic-plugin will be done.
